language: csharp
solution: Elephanet.sln
addons:
  postgresql: "9.4"

before_script:
  - psql -V
  - psql -c "CREATE USER store_user with PASSWORD 'my super secret password';" -U postgres
  - psql -c "CREATE DATABASE store;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE store to store_user;" -U postgres
